### ISSUE TITLE
Crashing my chrome

### ISSUE THREAD

**Issue by Sir-Nicholas** [Dumpster-Fire-Devs/SkyCast#1]
It starts using a billion gigabytes of ram when I install and use the extension. Pls fix

**Comment by 97-42** [comment]
> It starts using a billion gigabytes of ram when I install and use the extension. Pls fix

Hello, Thank you for using our extension
Can you please describe your issue thoroughly as I am unable to replicate your issue.
For example: Your Browser, Your RAM type and amount and any other information would be greatly appreciated. 
Cheers
D.F.D Team

**Comment by Sir-Nicholas** [comment]
> > It starts using a billion gigabytes of ram when I install and use the extension. Pls fix
> 
> Hello, Thank you for using our extension Can you please describe your issue thoroughly as I am unable to replicate your issue. For example: Your Browser, Your RAM type and amount and any other information would be greatly appreciated. Cheers D.F.D Team

I am using chrome. it is normal ram and it is windows 10
